version: 2

jobs:
  test:
    docker:
      - image: ekidd/rust-musl-builder
    steps:
      - checkout
      - run: cargo update
      - run: cargo build
      - run: cargo build --examples
      - run: cargo test
workflows:
  version: 2
  test-build-image:
    jobs:
      - test
